In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
seq = [1,2,3,4]
type(seq)

list

In [5]:
arr_seq = np.array(seq)
type(arr_seq)

numpy.ndarray

In [6]:
arr_seq.dtype

dtype('int32')

In [7]:
arr_seq.shape

(4,)

In [8]:
np.empty((2,2))

array([[2.12199579e-314, 1.26046550e-311],
       [5.39519685e-321, 6.95250701e-310]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.full((4), 10)

array([10, 10, 10, 10])

In [19]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(5, 11, 5)

array([ 5, 10])

np.arange(start, end, step)

In [22]:
x = np.arange(0, 20, 2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
x[2]

4

In [24]:
x[1:3]

array([2, 4])

In [25]:
x = np.empty((3,3))
x

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.93668167e-321],
       [6.23057348e-307, 1.42419530e-306, 0.00000000e+000]])

In [27]:
x[2,1]

1.4241952998709866e-306

In [43]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
x.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
x.reshape(2, 2, 3, 1)

array([[[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]]],


       [[[ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11]]]])

In [44]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
x.resize(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
x = np.arange(100).reshape(10, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
x[5:7, 5:7]

array([[55, 56],
       [65, 66]])

In [52]:
x = np.arange(27).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
x[...,1, :]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [54]:
x[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
x[:, np.newaxis,:,:].shape

(3, 1, 3, 3)

In [59]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
x = np.arange(27).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
x[[2,1], [1,0], [0,0]]

array([21,  9])

In [85]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
x[[0, 0, -1, -1], [0, -1, 0, -1]]


array([ 0,  3, 12, 15])

In [86]:
y = np.array([[0,0], [0,-1], [-1,0], [-1,-1]])
y = y.transpose()


In [87]:
x[y[0], y[1]]

array([ 0,  3, 12, 15])

In [96]:
corner_rows = np.array([0,1,2,3])

In [97]:
corner_cols = np.array([0,1,2,3])
x[corner_rows[:, np.newaxis], corner_cols]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
i = np.array([[0],
              [1],
              [2]])
j = np.array([0,1,2])
x[i,j]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [99]:
x = np.arange(-10,10)
x

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [100]:
x[x>8]

array([9])

In [101]:
x = np.array([1,2,3,4])
y = np.ones(4)
z = np.array([1,2,3,0])
zeros = np.zeros(4)

In [102]:
np.dot(x,y)

10.0

In [106]:
np.outer(x,y)

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [110]:
np.linalg.norm(x, 2)

5.477225575051661

In [112]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4,5],[3,4,5,3],[4,3,2,4]])

array([[2, 3, 4, 5],
       [3, 4, 5, 3],
       [4, 3, 2, 4]])

In [113]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
b

array([[2, 3, 4, 5],
       [3, 4, 5, 3],
       [4, 3, 2, 4]])

In [115]:
a.dot(b)

array([[20, 20, 20, 23],
       [47, 50, 53, 59]])

In [117]:
a@b

array([[20, 20, 20, 23],
       [47, 50, 53, 59]])

In [118]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
np.linalg.matrix_rank(a@b)

2

In [124]:
np.linalg.inv(b@b.T)

array([[ 0.2037037 , -0.11904762, -0.08201058],
       [-0.11904762,  0.15306122, -0.03741497],
       [-0.08201058, -0.03741497,  0.14247921]])

In [125]:
u, s, vT = np.linalg.svd(b, full_matrices=True)

In [126]:
u

array([[-0.58950154,  0.11713691, -0.79922893],
       [-0.61374045,  0.57833435,  0.53744956],
       [-0.52517673, -0.80734647,  0.26903733]])

In [127]:
s

array([12.21756758,  2.34933552,  1.7921119 ])

In [129]:
vT.T

array([[-4.19144917e-01, -5.36368254e-01,  6.08243346e-01,
        -4.08248290e-01],
       [-4.74644119e-01,  1.03309526e-01,  3.12047168e-01,
         8.16496581e-01],
       [-5.30143322e-01,  7.42987306e-01,  1.58509901e-02,
        -4.08248290e-01],
       [-5.63895874e-01, -3.86789478e-01, -7.29667968e-01,
         4.16333634e-16]])

In [131]:
A = np.array([[4, -5],[-2, 3]])
A

array([[ 4, -5],
       [-2,  3]])

In [132]:
b = np.array([-13, 9])

In [134]:
x = np.linalg.solve(A, b)
x

array([3., 5.])

In [135]:
A = np.ones((3,1,2,4))
B = np.ones((1,2,2,1))

(A*B).shape

(3, 2, 2, 4)

In [136]:
A*B

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [137]:
A = np.array([[1,2],
             [2,1]])
B = np.array([[3],
             [3]])
A+B

array([[4, 5],
       [5, 4]])